service: ${file(./config/service_name.yml):service}-${opt:stage, 'dev'}
provider:
  name: azure
  location: ${opt:location, 'West US'}
  environment:
    PROVIDER: 'azure'
plugins: 
  - serverless-azure-functions

functions:
  authenticateUser:
    handler: handler.authenticateUser
    events:
      - http: true,
        #x-azure-settings: #Uncommenting this will remove the need for the api key to be passed in the query string via ?code (see portal to access api key)
          #authLevel : anonymous 
  detachStripeAccount:
    handler: handler.detachStripeAccount
    events:
      - http: true,
        #x-azure-settings: #Uncommenting this will remove the need for the api key to be passed in the query string via ?code (see portal to access api key)
          #authLevel : anonymous 
              
package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'config/**'
    - '.gitignore'
    - '.git/**'